### ISSUE TITLE
No such file or directory: '/go/bin/gophernotes'

### ISSUE THREAD

**Issue by rkakrik** [gophergala2016/gophernotes#4]
After installing gophernotes I've got this message:
```
# github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq
could not determine kind of name for C.ZMQ_HWM
could not determine kind of name for C.ZMQ_MCAST_LOOP
could not determine kind of name for C.ZMQ_RECOVERY_IVL_MSEC
could not determine kind of name for C.ZMQ_SWAP
```
And running notebook:
```
Traceback` (most recent call last):
  File "/usr/lib/python3.5/site-packages/notebook/base/handlers.py", line 458, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 58, in post
    sm.create_session(path=path, kernel_name=kernel_name))
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 244, in start_kernel
    **kw)
  File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 190, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/go/bin/gophernotes
```

**Comment by rkakrik** [comment]
zeromq version is 4.1.3

**Comment by dwhitena** [comment]
This is a known issue I have seen on Fedora.  What OS are you using? Looking into this.

**Comment by dwhitena** [comment]
Possibly related: http://zeromq.org/docs:3-1-upgrade

**Comment by rkakrik** [comment]
I use Arch Linux. Maybe problem in "gozmq" package? By default it use zmq version 2.x and for 4.x it must be installed as "go get -tags zmq_4_x github.com/alecthomas/gozmq".

**Comment by dwhitena** [comment]
Ah, good find.  Yes, this appears to be the issue.  The version installed with Godep is the Gozmq install for ZeroMQ 2.2.X as described here: https://github.com/alecthomas/gozmq/blob/master/README.md.  I will try installing Gozmq with other tags and see what happens.  For the moment, I may need to add a caveat for ZeroMQ version.  It would be nice to remove this dependency if possible, though.  Maybe there is another option.

**Comment by dwhitena** [comment]
Some more useful info here: http://zeromq.org/bindings:go

**Comment by robbles** [comment]
Ran into this problem on OSX as well, and thought I'd share the solution here:

```
# follow normal instructions up until the error from "go get github.com/gophergala2016/gophernotes"

# install specific version of ZeroMQ library
brew tap homebrew/versions
brew install zeromq22
brew link --force zeromq22

# Rebuild gophernotes
go install github.com/gophergala2016/gophernotes

# Change path to gophernotes executable
which gophernotes
$EDITOR ~/.ipython/kernels/gophernotes/kernel.json

# Change .argv[0] in the JSON file to the absolute path to gophernotes
```

**Comment by dwhitena** [comment]
Thanks @robbles for the OSX fix.  I have updated the README to indicate the dependency on zeromq 2.2.X.  In the future, I will explore options to remove this dependency.  Please let me know if you have thoughts.

**Comment by robbles** [comment]
@dwhitena unless zeromq is fully backward compatible and there's an up-to-date wrapper so you can require the latest version, my only idea would be to look for a pure-go zeromq implementation. Not sure if that exists for Go?
Does IPython require a zeromq library to be installed?

**Comment by mmoya** [comment]
It works in Arch by installing gophernotes with the _zmq_4_x_ tag like `go get -tags zmq_4_x github.com/gophergala2016/gophernotes`.

**Comment by dwhitena** [comment]
@robbles Yes, see here for information on Jupyter kernels: https://ipython.org/ipython-doc/3/development/kernels.html.  However, I think @mmoya might have found a good solution for the time being.  I will add the tags comment to the README, for those that want to use 4.x.

**Comment by sadid** [comment]
using Archlinux with:
zeromq-4.5.1-1 
jupyter 4.1.0-4 
jupyter-notebook 4.2.0-1
$GOPATH = ~/.golang

and every other thing is pretty default. Installation done without any error but I get the kernel error when open a Golan notebook. I follow the `go get -tags zmq_4_x github.com/gophergala2016/gophernotes`  

here is the error:
`Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_name)
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/go/bin/gophernotes'
`
